[project]
name = "scenedetect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "albumentations>=2.0.8",
    "cityscapesscripts>=2.2.4",
    "evaluate>=0.4.6",
    "matplotlib>=3.11.1",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "pyyaml>=6.0.3",
    "tqdm>=4.70.0",
    "ultralytics>=8.4.120",
    "wandb>=0.28.2",
]
